on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs
        run: npm run gen
      - name: Export DSN for Left PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: output/pcbs/left.kicad_pcb
          dsn_file: output/pcbs/left.dsn
      - name: Export DSN for Right PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: output/pcbs/right.kicad_pcb
          dsn_file: output/pcbs/right.dsn
      - name: Autoroute Left PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: output/pcbs/left.dsn
          ses_file: output/pcbs/left.ses
      - name: Autoroute Right PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: output/pcbs/right.dsn
          ses_file: output/pcbs/right.ses
      - name: Import SES into Left PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: output/pcbs/left.kicad_pcb
          pcb_output_file: output/pcbs/left_routed.kicad_pcb
          ses_file: output/pcbs/left.ses
      - name: Import SES into Right PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: output/pcbs/right.kicad_pcb
          pcb_output_file: output/pcbs/right_routed.kicad_pcb
          ses_file: output/pcbs/right.ses
      - name: Export Gerbers for Left PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/left_routed.kicad_pcb
          gerbers_dir: output/gerbers/left
      - name: Export Gerbers for Right PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/right_routed.kicad_pcb
          gerbers_dir: output/gerbers/left
      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: samoklava-routed-pcbs-and-gerbers
          path: output
